### ISSUE TITLE
Create Rock GameObject

### ISSUE THREAD

**Issue by MWMaresch** [MWMaresch/Sonic_Platformer#1]
Difficulty: 1 (just collides with player)

literally copy the spikes class, but change its sprite and change the line that says player.getHurt() to player.collideWithGround(this.topLine) (found in checkCollisionWithPlayer)

you must also add its sprite to the sprite sheet in game.ts, which can be found below the Green Hill Zone sprites in the image we have
![r](https://cloud.githubusercontent.com/assets/15946561/20777003/1dc6ef3c-b732-11e6-9315-45377accdc9b.png)

**Comment by gsavchenko** [comment]
Please review for completion

**Comment by gsavchenko** [comment]
This has been completed.
