### ISSUE TITLE
Create Crab Meat GameObject

### ISSUE THREAD

**Issue by MWMaresch** [MWMaresch/Sonic_Platformer#4]
Difficulty: 3 (timers, creating projectiles, collision methods, and animations with the timers)

extends physgameobject
very similar to Motobug (so you can start by copying it), except with much more functionality
its walk speed is 0.5 instead of 1
it never needs to turn its sprite around, so remove scaleX lines

whenever it detects a wall or ledge, instead of turning around instantly, it stops moving and a timer is set to 120, and switch to the specified animation

in update, the timer decreases by 1

when the timer reaches 60, it should shoot 2 projectiles (one from each claw) that have gravity enabled 
the velocity of the projectiles should be upwards and facing away from each side (4 vertical speed, 1 horizontal speed). it should also switch to the specified animation

(if projectiles haven't been created yet, leave a comment line that says projectiles should be there)

when the timer reaches 0, the crab starts moving again in the opposite direction, and use the specified animation

animation rules: 
![r](https://cloud.githubusercontent.com/assets/15946561/20778071/58679b6c-b739-11e6-9b10-776dfeaf9751.png)

**Comment by gsavchenko** [comment]
Please review for completion
